name: moodlog
description: A mood tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # 상태 관리
  provider: ^6.1.1
  
  # 데이터베이스
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # 알림
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # 캘린더
  table_calendar: ^3.1.2
  
  # URL 실행 (YouTube)
  url_launcher: ^6.2.4
  
  # 날짜/시간
  intl: ^0.19.0
  
  # 설정 저장
  shared_preferences: ^2.2.3

  # iOS 스타일 아이콘
  cupertino_icons: ^1.0.8

  # 오디오 재생
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Sound/
  fonts:
    - family: BareunBatang
      fonts:
        - asset: assets/BareunBatangPro1.ttf
